---
branches:
  - main
projects:
  item-serialize-utils:
    path: ""
    model: virion
    type: library
    libs:
      - src: presentkim-pm/nbt-serializer/nbt-serializer
        version: "^2.0.0"
...
